### ISSUE TITLE
Excuse me, raise LocalEntryNotFoundError

### ISSUE THREAD

**Issue by zhang123-sys** [bwconrad/video-content-search#1]
![image](https://github.com/bwconrad/video-content-search/assets/63956071/d5c0c4c5-7e8c-473c-9b38-5d31375ac9be)

**Comment by zhang123-sys** [comment]
raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.

**Comment by bwconrad** [comment]
From your screenshot, I'm assuming you're using the huggingface space (correct me if I'm wrong). However I'm not able to reproduce this error. 

Does this happen every time you try running it? From what I can find, this error can sometimes be thrown if a hiccup in the network connection happens. 

Also does this error happen when you try using a different model?

**Comment by zhang123-sys** [comment]
ok， I run your code on centos 7 served.&nbsp;



---Original---
From: "Ben ***@***.***&gt;
Date: Wed, Jul 26, 2023 03:38 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [bwconrad/video-content-search] Excuse me, raiseLocalEntryNotFoundError (Issue #1)




 
From your screenshot, I'm assuming you're using the huggingface space (correct me if I'm wrong). However I'm not able to reproduce this error.
 
Does this happen every time you try running it? From what I can find, this error can sometimes be thrown if a hiccup in the network connection happens.
 
Also does this error happen when you try using a different model?

**Comment by bwconrad** [comment]
If you're running on a server then make sure it has internet access so it can download the model weights. The firewall could also be blocking the connection.

**Comment by zhang123-sys** [comment]
ok，centos7 server has no&nbsp;firewall

---Original---
From: "Ben ***@***.***&gt;
Date: Thu, Jul 27, 2023 04:18 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [bwconrad/video-content-search] Excuse me, raiseLocalEntryNotFoundError (Issue #1)




 
If you're running on a server then make sure it has internet access so it can download the model weights. The firewall could also be blocking the connection.

**Comment by bwconrad** [comment]
The error really has nothing to do with this repo's code and only with how your server's networking is configured. The only thing I can suggest is to try doing what is done [here](https://github.com/huggingface/transformers/issues/10067#issuecomment-794167650).
